// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220422064350_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Gender = "Male",
                            Name = "Chives",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 4,
                            Gender = "Male",
                            Name = "Rigatoni",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 1,
                            Gender = "Female",
                            Name = "Honeybun",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 2,
                            Gender = "Female",
                            Name = "Maple",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 3,
                            Gender = "Female",
                            Name = "Maggie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 6,
                            Gender = "Male",
                            Name = "William",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 5,
                            Gender = "Male",
                            Name = "Trashcan",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 10,
                            Gender = "Male",
                            Name = "Toast",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 100,
                            Gender = "Male",
                            Name = "Strahd",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 5,
                            Gender = "Male",
                            Name = "Ted",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
